CREATE TABLE users
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email         VARCHAR(100) UNIQUE                              NOT NULL,
    password_hash VARCHAR(255)                                     NOT NULL,
    access_token  TEXT,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    owner_id    INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
